apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pix-gateway-service
  description: "Gateway de entrada para transações PIX, responsável por roteamento e segurança"
  annotations:
    github.com/project-slug: emanueldeveloper82/pix-gateway-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: group:pix
  domain: financeiro
  system: system:pix-ecosystem
  providesApis:
    - pix-gateway-api 

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: pix-gateway-api
  description: "Especificação OpenAPI do Gateway Pix"
spec:
  type: openapi
  lifecycle: production
  owner: group:pix
  system: system:pix-ecosystem
  definition:
    $text: ./openapi.yaml 